# Generated by Django 3.0.7 on 2020-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathtestapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_by',
            field=models.IntegerField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default='M', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='modified_by',
            field=models.IntegerField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_no',
            field=models.IntegerField(default=None),
        ),
    ]
