# Generated by Django 3.0.7 on 2020-06-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathtestapi', '0002_auto_20200624_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(default='M', help_text='M=male,F=female,O=others', max_length=100),
        ),
    ]
